
def traduzir(texto, idioma):
    traducoes = {
        "harmonic_filter_analysis": {
            "en": "Harmonic Filter Analysis",
            "zh": "谐波滤波器分析",
            "de": "Analyse von Harmonikfiltern",
            "it": "Analisi del filtro armonico",
            "es": "Análisis de filtro armónico",
            "ru": "Анализ гармонических фильтров",
            "fr": "Analyse du filtre harmonique",
            "pt": "Análise de Filtro Harmônico",
        },
        "⚙️ Filtro": {
            "en": "⚙️ Filter",
            "zh": "⚙️ 过滤器",
            "de": "⚙️ Filter",
            "it": "⚙️ Filtro",
            "es": "⚙️ Filtro",
            "ru": "⚙️ Фильтр",
            "fr": "⚙️ Filtre",
            "pt": "⚙️ Filtro",
        },
        "⚡Transformador": {
            "en": "⚡Transformer",
            "zh": "⚡ 变压器",
            "de": "⚡Transformator",
            "it": "⚡Trasformatore",
            "es": "⚡Transformador",
            "ru": "⚡Трансформатор",
            "fr": "⚡Transformateur",
            "pt": "⚡Transformador",
        },
        "💾 Leituras de Corrente": {
            "en": "💾 Current Readings",
            "zh": "💾 电流读数",
            "de": "💾 Strommessungen",
            "it": "💾 Letture di Corrente",
            "es": "💾 Lecturas de Corriente",
            "ru": "💾 Измерения Тока",
            "fr": "💾 Mesures de Courant",
            "pt": "💾 Leituras de Corrente",
        },
        "📈 Resposta de Frequência": {
            "en": "📈 Frequency Response",
            "zh": "📈 频率响应",
            "de": "📈 Frequenzantwort",
            "it": "📈 Risposta in Frequenza",
            "es": "📈 Respuesta de Frecuencia",
            "ru": "📈 Частотная Характеристика",
            "fr": "📈 Réponse en Fréquence",
            "pt": "📈 Resposta de Frequência",
        },
        "📊 Tensão | Corrente | Potência": {
            "en": "📊 Voltage | Current | Power",
            "zh": "📊 电压 | 电流 | 功率",
            "de": "📊 Spannung | Strom | Leistung",
            "it": "📊 Tensione | Corrente | Potenza",
            "es": "📊 Voltaje | Corriente | Potencia",
            "ru": "📊 Напряжение | Ток | Мощность",
            "fr": "📊 Tension | Courant | Puissance",
            "pt": "📊 Tensão | Corrente | Potência",
        },
        "Tipo de Filtro": {
            "en": "Filter Type",
            "zh": "滤波器类型",
            "de": "Filtertyp",
            "it": "Tipo di Filtro",
            "es": "Tipo de Filtro",
            "ru": "Тип Фильтра",
            "fr": "Type de Filtre",
            "pt": "Tipo de Filtro",
        },
        "Filtro Amortecedor": {
            "en": "Damping Filter",
            "zh": "阻尼滤波器",
            "de": "Dämpfungsfilter",
            "it": "Filtro Smorzatore",
            "es": "Filtro Amortiguador",
            "ru": "Демпфирующий Фильтр",
            "fr": "Filtre d'Amortissement",
            "pt": "Filtro Amortecedor",
        },
        "Filtro Sintonizado": {
            "en": "Tuned Filter",
            "zh": "调谐滤波器",
            "de": "Abgestimmter Filter",
            "it": "Filtro Sintonizzato",
            "es": "Filtro Sintonizado",
            "ru": "Настроенный Фильтр",
            "fr": "Filtre Accordé",
            "pt": "Filtro Sintonizado",
        },
        "Filtro Tipo C": {
            "en": "Type C Filter",
            "zh": "C型滤波器",
            "de": "Typ-C-Filter",
            "it": "Filtro Tipo C",
            "es": "Filtro Tipo C",
            "ru": "Фильтр Типа C",
            "fr": "Filtre Type C",
            "pt": "Filtro Tipo C",
        },
        "Tensão (kV)": {
            "en": "Voltage (kV)",
            "zh": "电压（千伏）",
            "de": "Spannung (kV)",
            "it": "Tensione (kV)",
            "es": "Tensión (kV)",
            "ru": "Напряжение (кВ)",
            "fr": "Tension (kV)",
            "pt": "Tensão (kV)",
        },
        "Potência Reativa (MVAr)": {
            "en": "Reactive Power (MVAr)",
            "zh": "无功功率（兆乏）",
            "de": "Blindleistung (MVAr)",
            "it": "Potenza Reattiva (MVAr)",
            "es": "Potencia Reactiva (MVAr)",
            "ru": "Реактивная Мощность (МВАр)",
            "fr": "Puissance Réactive (MVAr)",
            "pt": "Potência Reativa (MVAr)",
        },
        "Harmonica Principal": {
            "en": "Main Harmonic",
            "zh": "主谐波",
            "de": "Hauptoberwelle",
            "it": "Armonica Principale",
            "es": "Armónica Principal",
            "ru": "Основная Гармоника",
            "fr": "Harmonique Principale",
            "pt": "Harmônica Principal",
        },
        "Dessintonia (%)": {
            "en": "Detuning (%)",
            "zh": "失谐（%）",
            "de": "Verstimmung (%)",
            "it": "Dissintonia (%)",
            "es": "Desintonización (%)",
            "ru": "Расстройка (%)",
            "fr": "Désaccord (%)",
            "pt": "Dessintonia (%)",
        },
        "Fator de Qualidade do Filtro": {
            "en": "Filter Quality Factor",
            "zh": "滤波器品质因数",
            "de": "Filtergütefaktor",
            "it": "Fattore di Qualità del Filtro",
            "es": "Factor de Calidad del Filtro",
            "ru": "Коэффициент Качества Фильтра",
            "fr": "Facteur de Qualité du Filtre",
            "pt": "Fator de Qualidade do Filtro",
        },
        "Conteúdo Harmônico da Corrente de Carga": {
            "en": "Load Current Harmonic Content",
            "zh": "负载电流谐波含量",
            "de": "Harmonischer Gehalt des Laststroms",
            "it": "Contenuto Armonico della Corrente di Carico",
            "es": "Contenido Armónico de la Corriente de Carga",
            "ru": "Гармоническое Содержание Тока Нагрузки",
            "fr": "Contenu Harmonique du Courant de Charge",
            "pt": "Conteúdo Harmônico da Corrente de Carga",
        },
        "Percentual de Resistência (%)": {
            "en": "Resistance Percentage (%)",
            "zh": "电阻百分比 (%)",
            "de": "Widerstandsprozentsatz (%)",
            "it": "Percentuale di Resistenza (%)",
            "es": "Porcentaje de Resistencia (%)",
            "ru": "Процент Сопротивления (%)",
            "fr": "Pourcentage de Résistance (%)",
            "pt": "Percentual de Resistência (%)",
        },
        "Percentual de Reatância (%)": {
            "en": "Reactance Percentage (%)",
            "zh": "电抗百分比 (%)",
            "de": "Reaktanzprozentsatz (%)",
            "it": "Percentuale di Reattanza (%)",
            "es": "Porcentaje de Reactancia (%)",
            "ru": "Процент Реактивного Сопротивления (%)",
            "fr": "Pourcentage de Réactance (%)",
            "pt": "Percentual de Reatância (%)",
        },
        "Potência Nominal (MVA)": {
            "en": "Rated Power (MVA)",
            "zh": "额定功率（兆伏安）",
            "de": "Nennleistung (MVA)",
            "it": "Potenza Nominale (MVA)",
            "es": "Potencia Nominal (MVA)",
            "ru": "Номинальная Мощность (МВА)",
            "fr": "Puissance Nominale (MVA)",
            "pt": "Potência Nominal (MVA)",
        },
        "Transformador": {
            "en": "Transformer",
            "zh": "变压器",
            "de": "Transformator",
            "it": "Trasformatore",
            "es": "Transformador",
            "ru": "Трансформатор",
            "fr": "Transformateur",
            "pt": "Transformador",
        },
        "Quantidade de Harmônicas": {
            "en": "Number of Harmonics",
            "zh": "谐波数量",
            "de": "Anzahl der Harmonischen",
            "it": "Numero di Armoniche",
            "es": "Número de Armónicos",
            "ru": "Количество Гармоник",
            "fr": "Nombre d'Harmoniques",
            "pt": "Quantidade de Harmônicas",
        },
        "Harmônica [h]": {
            "en": "Harmonic [h]",
            "zh": "谐波 [h]",
            "de": "Harmonische [h]",
            "it": "Armonica [h]",
            "es": "Armónica [h]",
            "ru": "Гармоника [h]",
            "fr": "Harmonique [h]",
            "pt": "Harmônica [h]",
        },
        "Corrente [A]": {
            "en": "Current [A]",
            "zh": "电流 [安]",
            "de": "Strom [A]",
            "it": "Corrente [A]",
            "es": "Corriente [A]",
            "ru": "Ток [A]",
            "fr": "Courant [A]",
            "pt": "Corrente [A]",
        },
        "Resposta de Frequência": {
            "en": "Frequency Response",
            "zh": "频率响应",
            "de": "Frequenzgang",
            "it": "Risposta in Frequenza",
            "es": "Respuesta de Frecuencia",
            "ru": "Частотная Характеристика",
            "fr": "Réponse en Fréquence",
            "pt": "Resposta de Frequência",
        },
        "Harmônica de Mínima Impedância do Filtro": {
            "en": "Harmonic of Minimum Filter Impedance",
            "zh": "滤波器最小阻抗的谐波",
            "de": "Harmonische der minimalen Filterimpedanz",
            "it": "Armonica dell'impedenza minima del filtro",
            "es": "Armónica de la impedancia mínima del filtro",
            "ru": "Гармоника минимального импеданса фильтра",
            "fr": "Harmonique de l'impédance minimale du filtre",
            "pt": "Harmônica de Mínima Impedância do Filtro",
        },
        "Corrente / Corrente de Base do Transformador": {
            "en": "Current / Transformer Base Current",
            "zh": "电流 / 变压器基础电流",
            "de": "Strom / Basisstrom des Transformators",
            "it": "Corrente / Corrente di base del trasformatore",
            "es": "Corriente / Corriente base del transformador",
            "ru": "Ток / Базовый ток трансформатора",
            "fr": "Courant / Courant de base du transformateur",
            "pt": "Corrente / Corrente de Base do Transformador",
        },
            "Corrente": {
                "en": "Current",
                "zh": "电流",
                "de": "Strom",
                "it": "Corrente",
                "es": "Corriente",
                "ru": "Ток",
                "fr": "Courant",
                "pt": "Corrente",
            },
        "Potência nos Elementos do Filtro": {
            "en": "Power in Filter Elements",
            "zh": "滤波器元件中的功率",
            "de": "Leistung in Filterelementen",
            "it": "Potenza negli elementi del filtro",
            "es": "Potencia en los elementos del filtro",
            "ru": "Мощность в элементах фильтра",
            "fr": "Puissance dans les éléments du filtre",
            "pt": "Potência nos Elementos do Filtro",
        },
        "Conteúdo Harmônico da Corrente [pu]": {
            "en": "Current Harmonic Content [pu]",
            "zh": "电流谐波含量（单位制）",
            "de": "Harmonischer Stromgehalt [pu]",
            "it": "Contenuto Armonico della Corrente [pu]",
            "es": "Contenido Armónico de la Corriente [pu]",
            "ru": "Гармоническое Содержание Тока [pu]",
            "fr": "Contenu Harmonique du Courant [pu]",
            "pt": "Conteúdo Harmônico da Corrente [pu]",
        },
        "Harmônica": {
            "en": "Harmonic",
            "zh": "谐波",
            "de": "Harmonische",
            "it": "Armonica",
            "es": "Armónica",
            "ru": "Гармоника",
            "fr": "Harmonique",
            "pt": "Harmônica",
        },
        "Corrente [pu]": {
            "en": "Current [pu]",
            "zh": "电流 [单位制] [pu]",
            "de": "Strom [pu]",
            "it": "Corrente [pu]",
            "es": "Corriente [pu]",
            "ru": "Ток [pu]",
            "fr": "Courant [pu]",
            "pt": "Corrente [pu]",
        },
        "Conteúdo Harmônico da Corrente [A]": {
            "en": "Current Harmonic Content [A]",
            "zh": "电流谐波含量（安培）",
            "de": "Stromharmonische Inhalte [A]",
            "it": "Contenuto Armonico della Corrente [A]",
            "es": "Contenido Armónico de la Corriente [A]",
            "ru": "Гармоническое Содержание Тока [A]",
            "fr": "Contenu Harmonique du Courant [A]",
            "pt": "Conteúdo Harmônico da Corrente [A]",
        },
        "Harmônica": {
            "en": "Harmonic",
            "zh": "谐波",
            "de": "Harmonische",
            "it": "Armonica",
            "es": "Armónica",
            "ru": "Гармоника",
            "fr": "Harmonique",
            "pt": "Harmônica",
        },
        "Corrente [A]": {
            "en": "Current [A]",
            "zh": "电流 [安] [A]",
            "de": "Strom [A]",
            "it": "Corrente [A]",
            "es": "Corriente [A]",
            "ru": "Ток [A]",
            "fr": "Courant [A]",
            "pt": "Corrente [A]",
        },
        "Filtro": {
            "en": "Filter",
            "zh": "滤波器",
            "de": "Filter",
            "it": "Filtro",
            "es": "Filtro",
            "ru": "Фильтр",
            "fr": "Filtre",
            "pt": "Filtro",
        },
        "Transformador": {
            "en": "Transformer",
            "zh": "变压器",
            "de": "Transformator",
            "it": "Trasformatore",
            "es": "Transformador",
            "ru": "Трансформатор",
            "fr": "Transformateur",
            "pt": "Transformador",
        },
        "Equivalente": {
            "en": "Equivalent",
            "zh": "等效的",
            "de": "Äquivalent",
            "it": "Equivalente",
            "es": "Equivalente",
            "ru": "Эквивалент",
            "fr": "Équivalent",
            "pt": "Equivalente",
        },
        "Relação entre Módulo de Impedância e Frequência": {
            "en": "Relation between Impedance Module and Frequency",
            "zh": "阻抗模值与频率的关系",
            "de": "Beziehung zwischen Impedanzmodul und Frequenz",
            "it": "Relazione tra Modulo di Impedenza e Frequenza",
            "es": "Relación entre Módulo de Impedancia y Frecuencia",
            "ru": "Связь между модулем импеданса и частотой",
            "fr": "Relation entre le Module d'Impédance et la Fréquence",
            "pt": "Relação entre Módulo de Impedância e Frequência",
        },
        "Harmônica": {
            "en": "Harmonic",
            "zh": "谐波",
            "de": "Harmonisch",
            "it": "Armonica",
            "es": "Armónica",
            "ru": "Гармоника",
            "fr": "Harmonique",
            "pt": "Harmônica",
        },
        "Módulo [pu]": {
            "en": "Module [pu]",
            "zh": "模数 [单位制] [pu]",
            "de": "Modul [pu]",
            "it": "Modulo [pu]",
            "es": "Módulo [pu]",
            "ru": "Модуль [pu]",
            "fr": "Module [pu]",
            "pt": "Módulo [pu]",
        },
        "Componente": {
            "en": "Component",
            "zh": "组件",
            "de": "Komponente",
            "it": "Componente",
            "es": "Componente",
            "ru": "Компонент",
            "fr": "Composant",
            "pt": "Componente",
        },
        "Harmônica de Mínima Impedância do Filtro": {
            "en": "Filter Minimum Impedance Harmonic",
            "zh": "滤波器最小阻抗的谐波",
            "de": "Filter Minimale Impedanz Harmonik",
            "it": "Armonica di Impedenza Minima del Filtro",
            "es": "Armónica de Mínima Impedancia del Filtro",
            "ru": "Минимальная Гармоника Импеданса Фильтра",
            "fr": "Harmonique d'Impédance Minimale du Filtre",
            "pt": "Harmônica de Mínima Impedância do Filtro",
        },
        "Fase [°]": {
            "en": "Phase [°]",
            "zh": "相位 [度]",
            "de": "Phase [°]",
            "it": "Fase [°]",
            "es": "Fase [°]",
            "ru": "Фаза [°]",
            "fr": "Phase [°]",
            "pt": "Fase [°]",
        },
        "Relação entre Fase da Impedância e Frequência": {
            "en": "Relation between Impedance Phase and Frequency",
            "zh": "阻抗相位与频率关系",
            "de": "Beziehung zwischen Impedanzphase und Frequenz",
            "it": "Relazione tra Fase dell'Impedenza e Frequenza",
            "es": "Relación entre Fase de la Impedancia y Frecuencia",
            "ru": "Связь между фазой импеданса и частотой",
            "fr": "Relation entre la Phase de l'Impédance et la Fréquence",
            "pt": "Relação entre Fase da Impedância e Frequência",
        },
        "Resistor [W]": {
            "en": "Resistor [W]",
            "zh": "电阻器 [W]",
            "de": "Widerstand [W]",
            "it": "Resistore [W]",
            "es": "Resistor [W]",
            "ru": "Резистор [Вт]",
            "fr": "Résistance [W]",
            "pt": "Resistor [W]",
        },
        "Indutor [VAr]": {
            "en": "Inductor [VAr]",
            "zh": "电感器 [VAr]",
            "de": "Induktivität [VAr]",
            "it": "Induttore [VAr]",
            "es": "Inductor [VAr]",
            "ru": "Индуктор [вар]",
            "fr": "Inductance [VAr]",
            "pt": "Indutor [VAr]",
        },
        "Capacitor [VAr]": {
            "en": "Capacitor [VAr]",
            "zh": "电容器 [VAr]",
            "de": "Kondensator [VAr]",
            "it": "Condensatore [VAr]",
            "es": "Capacitor [VAr]",
            "ru": "Конденсатор [вар]",
            "fr": "Condensateur [VAr]",
            "pt": "Capacitor [VAr]",
        },
        "Potência nos Elementos do Filtro": {
            "en": "Power in Filter Elements",
            "zh": "滤波器元件中的功率",
            "de": "Leistung in Filterelementen",
            "it": "Potenza negli elementi del filtro",
            "es": "Potencia en elementos del filtro",
            "ru": "Мощность в элементах фильтра",
            "fr": "Puissance dans les éléments du filtre",
            "pt": "Potência nos Elementos do Filtro",
        },
        "Harmônicas": {
            "en": "Harmonics",
            "zh": "谐波",
            "de": "Harmonische",
            "it": "Armoniche",
            "es": "Armónicas",
            "ru": "Гармоники",
            "fr": "Harmoniques",
            "pt": "Harmônicas",
        },
        "Potência [VA]": {
            "en": "Power [VA]",
            "zh": "功率 [伏安] [VA]",
            "de": "Leistung [VA]",
            "it": "Potenza [VA]",
            "es": "Potencia [VA]",
            "ru": "Мощность [VA]",
            "fr": "Puissance [VA]",
            "pt": "Potência [VA]",
        },
        "Corrente Total / Corrente Nominal dos Capacitores": {
            "en": "Total Current / Rated Capacitor Current",
            "zh": "总电流 / 电容器额定电流",
            "de": "Gesamtstrom / Nennstrom der Kondensatoren",
            "it": "Corrente Totale / Corrente Nominale dei Condensatori",
            "es": "Corriente Total / Corriente Nominal de los Capacitores",
            "ru": "Общий ток / Номинальный ток конденсаторов",
            "fr": "Courant Total / Courant Nominal des Condensateurs",
            "pt": "Corrente Total / Corrente Nominal dos Capacitores",
        },
        "Resistor": {
            "en": "Resistor",
            "zh": "电阻器",
            "de": "Widerstand",
            "it": "Resistore",
            "es": "Resistor",
            "ru": "Резистор",
            "fr": "Résistance",
            "pt": "Resistor",
        },
        "Indutor": {
            "en": "Inductor",
            "zh": "电感器",
            "de": "Induktivität",
            "it": "Induttore",
            "es": "Inductor",
            "ru": "Индуктор",
            "fr": "Inductance",
            "pt": "Indutor",
        },
        "Capacitor": {
            "en": "Capacitor",
            "zh": "电容器",
            "de": "Kondensator",
            "it": "Condensatore",
            "es": "Capacitor",
            "ru": "Конденсатор",
            "fr": "Condensateur",
            "pt": "Capacitor",
        },
        "Total": {
            "en": "Total",
            "zh": "总",
            "de": "Gesamt",
            "it": "Totale",
            "es": "Total",
            "ru": "Общий",
            "fr": "Total",
            "pt": "Total",
        },
        "Tensão / Tensão de Fase": {
            "en": "Voltage / Phase Voltage",
            "zh": "电压 / 相电压",
            "de": "Spannung / Phasenspannung",
            "it": "Tensione / Tensione di Fase",
            "es": "Voltaje / Voltaje de Fase",
            "ru": "Напряжение / Фазное напряжение",
            "fr": "Tension / Tension de phase",
            "pt": "Tensão / Tensão de Fase",
        },
        "Harmônicas": {
            "en": "Harmonics",
            "zh": "谐波",
            "de": "Harmonischen",
            "it": "Armoniche",
            "es": "Armónicas",
            "ru": "Гармоники",
            "fr": "Harmoniques",
            "pt": "Harmônicas",
        },
        "Tensão": {
            "en": "Voltage",
            "zh": "电压",
            "de": "Spannung",
            "it": "Tensione",
            "es": "Voltaje",
            "ru": "Напряжение",
            "fr": "Tension",
            "pt": "Tensão",
        },
        "Transformador": {
            "en": "Transformer",
            "zh": "变压器",
            "de": "Transformator",
            "it": "Trasformatore",
            "es": "Transformador",
            "ru": "Трансформатор",
            "fr": "Transformateur",
            "pt": "Transformador",
        },
        "Filtro": {
            "en": "Filter",
            "zh": "滤波器",
            "de": "Filter",
            "it": "Filtro",
            "es": "Filtro",
            "ru": "Фильтр",
            "fr": "Filtre",
            "pt": "Filtro",
        },
        "Carga": {
            "en": "Load",
            "zh": "负载",
            "de": "Last",
            "it": "Carico",
            "es": "Carga",
            "ru": "Нагрузка",
            "fr": "Charge",
            "pt": "Carga",
        },
        "Corrente / Corrente Nominal do Transformador": {
            "en": "Current / Nominal Transformer Current",
            "zh": "电流 / 变压器额定电流",
            "de": "Strom / Nennstrom des Transformators",
            "it": "Corrente / Corrente Nominale del Trasformatore",
            "es": "Corriente / Corriente Nominal del Transformador",
            "ru": "Ток / Номинальный ток трансформатора",
            "fr": "Courant / Courant nominal du transformateur",
            "pt": "Corrente / Corrente Nominal do Transformador",
        },
        "Harmônicas": {
            "en": "Harmonics",
            "zh": "谐波",
            "de": "Harmonische",
            "it": "Armoniche",
            "es": "Armónicas",
            "ru": "Гармоники",
            "fr": "Harmoniques",
            "pt": "Harmônicas",
        },
        "Corrente / [{} A]": {
            "en": "Current / [{} A]",
            "zh": "电流 / [{} A]",
            "de": "Strom / [{} A]",
            "it": "Corrente / [{} A]",
            "es": "Corriente / [{} A]",
            "ru": "Ток / [{} A]",
            "fr": "Courant / [{} A]",
            "pt": "Corrente / [{} A]",
        }


    }
    return traducoes.get(texto, {}).get(idioma, texto)
